definitions:
  user.UserID:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Get user id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserID'
      summary: Get user id
swagger: "2.0"
